Add secret-check workflow

diff --git a/.github/workflows/secret-check.yml b/.github/workflows/secret-check.yml
--- a/.github/workflows/secret-check.yml
+++ b/.github/workflows/secret-check.yml
@@ -9,3 +9,10 @@ job:
     env:
       - name: Access secret
         run: echo "The secret value is ${{ secrets.APP_TOKEN}}"
+    run: |
+          if [ -n "$APP_TOKEN" ]; then
+            echo "APP_TOKEN is set for this job"
+          else
+            echo "APP_TOKEN is missing"
+            exit 1
+          fi      
